name = "HerbInterpret"
uuid = "5bbddadd-02c5-4713-84b8-97364418cca7"
version = "1.0.0"
authors = ["Tilman Hinnerichs <t.r.hinnerichs@tudelft.nl>", "Jaap de Jong <jaapdejong15@gmail.com>", "Sebastijan Dumancic <s.dumancic@tudelft.nl>", "Reuben Gardos Reid <R.J.GardosReid@tudelft.nl>"]

[deps]
HerbCore = "2b23ba43-8213-43cb-b5ea-38c12b45bd45"
HerbGrammar = "4ef9e186-2fe5-4b24-8de7-9f7291f24af7"
HerbSpecification = "6d54aada-062f-46d8-85cf-a1ceaf058a06"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"

[compat]
HerbCore = "1"
HerbGrammar = "1"
HerbSpecification = "1"
MLStyle = "0.4.17"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
