name: Monthly contributor report
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

permissions:
  contents: read

jobs:
  contributor_report:
    name: contributor report
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
          
      - name: Run contributor action
        uses: reubenj/contributors@v1.4.4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          START_DATE: ""
          END_DATE: ""
          ORGANIZATION: Herb-AI
          SPONSOR_INFO: "True"
          LINK_TO_PROFILE: "True"

      - name: Rename file and remove JSON
        shell: bash
        run: |
          rm contributors.json
          mv contributors.md CONTRIBUTORS.md
          
      - name: Add and commit CONTRIBUTORS.md
        uses: EndBug/add-and-commit@v9 
        with:
          message: "Monthly contributors report"
          default_author: github_actions

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update org-level contributors
