name: Documentation

on:
  push:
    branches:
      - documentation # update to match your development branch (master, main, dev, trunk, ...)
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyterlab nbconvert
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - name: Install dependencies
        run: julia --project=docs/ -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.develop("HerbCore");
          Pkg.develop("HerbData");
          Pkg.develop("HerbGrammar");
          Pkg.develop("HerbInterpret");
          Pkg.develop("HerbConstraints");
          Pkg.develop("HerbSearch");
          Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ docs/make.jl
